# Site Settings
encoding                 : "utf-8"
locale                   : "en"
title                    : "Jens Ochsenmeier"
title_separator          : "-"
description              : "My personal homepage. Here you can find information about me and my projects and a lot of university related stuff."
favicon                  : "/assets/images/me.jpg"
avatar                   : "/assets/images/me.jpg"
url                      : "https://jens-ox.de" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog" leave blank if no subpath

# Site Author
author:
  name                   : "Jens Ochsenmeier" # appears in the footer and atom feed

atom_feed:
  path                   : # blank (default) uses feed.xml

og_image                 : "/assets/images/me.jpg" # Open Graph/Twitter default site image, optional for seo and social sharing

# Social sharing
twitter:
  username               : "jochsenmeier" # optional, for social sharing

# Reading Files
include:
  - _pages
# Files excluded from Jekyll builds
exclude:
- README.md
- LICENSE
- Gemfile
- Gemfile.lock


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /blog/:title/
paginate: 5 # amount of posts to show
paginate_path: "/blog/page:num/"
timezone: # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-feed


# Front matter defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      comments: false
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      share: true

assets:
  compress:
    css:  sass
    js:   uglifier