# Site Settings
encoding                 : "utf-8"
locale                   : "en"
title                    : "Jens"
title_separator          : "-"
description              : "My personal homepage. Here you can find information about me and my projects and a lot of university related stuff."
favicon                  : "/static/images/favicon.ico"
avatar                   : "/static/images/me.jpg"
avatar_small             : "/static/images/me_small.jpg"
baseurl                  : "" # the subpath of your site, e.g. "/blog" leave blank if no subpath

# Site Author
author:
  name                   : "Jens Ox" # appears in the footer and atom feed

atom_feed:
  path                   : # blank (default) uses feed.xml

og_image                 : "/static/images/me.jpg" # Open Graph/Twitter default site image, optional for seo and social sharing

# Social sharing
twitter:
  username               : "jens_ox" # optional, for social sharing

# Reading Files
include:
  - _pages
# Files excluded from Jekyll builds
exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.js



# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Outputting
permalink: /blog/:title/
paginate: 5 # amount of posts to show
paginate_path: "/blog/page:num/"
timezone: DE # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

plugins:
  - jekyll-paginate
  - jekyll-feed

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-feed


# Front matter defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      comments: false
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      share: true